export const MANIFEST_FIELDS = [
  'productName',
  'itemName',
  'strain',
  'packageTag',
  'tag',
  'retailId',
  'lotNumber',
  'batchNumber',
  'batch',
  'sourceBatchNumbers',
  'manufacturedDate',
  'packagedDate',
  'expirationDate',
  'sellByDate',
  'useByDate',
  'thcPercent',
  'thcMgG',
  'thcMgPackage',
  'cbdPercent',
  'cbdMgG',
  'cbdMgPackage',
  'tacPercent',
  'tacMgG',
  'labFacilityName',
  'testPerformedDate',
  'coaDocumentId',
  'brandName',
  'quantity',
  'unitOfMeasure',
  'unitIndex',
  'retailIdSource',
] as const;

export const MANIFEST_FIELD_OPTIONS = MANIFEST_FIELDS.map((field) => ({
  value: field,
  label: field,
}));
