export const MANIFEST_FIELDS = [
  'productName',
  'itemName',
  'strain',
  'packageTag',
  'tag',
  'retailId',
  'lotNumber',
  'batchNumber',
  'batch',
  'sourceBatchNumbers',
  'manufacturedDate',
  'packagedDate',
  'expirationDate',
  'sellByDate',
  'useByDate',
  'thcPercent',
  'thcMgG',
  'thcMgPackage',
  'thcMgServing',
  'thcPerServing',
  'cbdPercent',
  'cbdMgG',
  'cbdMgPackage',
  'tacPercent',
  'tacMgG',
  'tacMgPackage',
  'tacMgServing',
  'tacPerServing',
  'totalActiveCannabinoidsPercent',
  'totalActiveCannabinoidsMgG',
  'totalActiveCannabinoidsMgPackage',
  'totalActiveCannabinoidsMgServing',
  'totalCannabinoidsPercent',
  'totalCannabinoidsMgG',
  'servingSize',
  'servingCount',
  'numberOfDoses',
  'servingsPerPackage',
  'labFacilityName',
  'testPerformedDate',
  'coaDocumentId',
  'brandName',
  'quantity',
  'unitOfMeasure',
  'unitIndex',
  'retailIdSource',
  'retailIdCount',
] as const;

const MANIFEST_PICKER_HIDDEN_FIELDS = new Set<(typeof MANIFEST_FIELDS)[number]>([
  'tag',
  'batch',
  'thcPerServing',
  'tacPerServing',
  'totalActiveCannabinoidsPercent',
  'totalActiveCannabinoidsMgG',
  'totalActiveCannabinoidsMgPackage',
  'totalActiveCannabinoidsMgServing',
  'totalCannabinoidsPercent',
  'totalCannabinoidsMgG',
  'numberOfDoses',
  'servingsPerPackage',
]);

const MANIFEST_FIELD_LABELS: Partial<Record<(typeof MANIFEST_FIELDS)[number], string>> = {
  productName: 'Product name',
  itemName: 'Item name',
  packageTag: 'Package tag',
  retailId: 'Retail ID',
  lotNumber: 'Lot #',
  batchNumber: 'Batch #',
  sourceBatchNumbers: 'Source batches',
  manufacturedDate: 'MFG date',
  packagedDate: 'Packaged date',
  expirationDate: 'EXP date',
  sellByDate: 'Sell-by date',
  useByDate: 'Use-by date',
  thcPercent: 'THC %',
  thcMgG: 'THC mg/g',
  thcMgPackage: 'THC mg/pkg',
  thcMgServing: 'THC mg/serving',
  cbdPercent: 'CBD %',
  cbdMgG: 'CBD mg/g',
  cbdMgPackage: 'CBD mg/pkg',
  tacPercent: 'TAC %',
  tacMgG: 'TAC mg/g',
  tacMgPackage: 'TAC mg/pkg',
  tacMgServing: 'TAC mg/serving',
  servingSize: 'Serving size',
  servingCount: 'Serving count',
  labFacilityName: 'Lab facility',
  testPerformedDate: 'Test date',
  coaDocumentId: 'COA document',
  brandName: 'Brand name',
  unitOfMeasure: 'Unit of measure',
  unitIndex: 'Unit #',
  retailIdSource: 'Retail ID source',
  retailIdCount: 'Retail ID count',
};

export const MANIFEST_FIELD_OPTIONS = MANIFEST_FIELDS.filter((field) => !MANIFEST_PICKER_HIDDEN_FIELDS.has(field)).map((field) => ({
  value: field,
  label: MANIFEST_FIELD_LABELS[field] ?? field,
}));
